blocklists = []
block_contents = []
# wood_polished
wood_polished = []
wood_polished_content = '{\n    "defaultMaterial": "lumiext:wood_polished"\n}'
blocklists.append(wood_polished)
block_contents.append(wood_polished_content)
# wood_polished -> planks
wood_polished.append("aspen_planks")
wood_polished.append("baobab_planks")
wood_polished.append("blue_enchanted_planks")
wood_polished.append("cherry_planks")
wood_polished.append("cika_planks")
wood_polished.append("cypress_planks")
wood_polished.append("ebony_planks")
wood_polished.append("fir_planks")
wood_polished.append("green_enchanted_planks")
wood_polished.append("holly_planks")
wood_polished.append("jacaranda_planks")
wood_polished.append("mahogany_planks")
wood_polished.append("mangrove_planks")
wood_polished.append("maple_planks")
wood_polished.append("pine_planks")
wood_polished.append("rainbow_eucalyptus_planks")
wood_polished.append("redwood_planks")
wood_polished.append("skyris_planks")
wood_polished.append("willow_planks")
wood_polished.append("witch_hazel_planks")
wood_polished.append("zelkova_planks")
wood_polished.append("sythian_planks")
wood_polished.append("embur_planks")
wood_polished.append("palm_planks")
wood_polished.append("lament_planks")
wood_polished.append("bulbis_planks")
wood_polished.append("nightshade_planks")
wood_polished.append("ether_planks")
# wood_polished -> doors
wood_polished.append("aspen_door")
wood_polished.append("baobab_door")
wood_polished.append("blue_enchanted_door")
wood_polished.append("cherry_door")
wood_polished.append("cika_door")
wood_polished.append("cypress_door")
wood_polished.append("ebony_door")
wood_polished.append("fir_door")
wood_polished.append("green_enchanted_door")
wood_polished.append("holly_door")
wood_polished.append("jacaranda_door")
wood_polished.append("mahogany_door")
wood_polished.append("mangrove_door")
wood_polished.append("maple_door")
wood_polished.append("pine_door")
wood_polished.append("rainbow_eucalyptus_door")
wood_polished.append("redwood_door")
wood_polished.append("skyris_door")
wood_polished.append("willow_door")
wood_polished.append("witch_hazel_door")
wood_polished.append("zelkova_door")
wood_polished.append("sythian_door")
wood_polished.append("embur_door")
wood_polished.append("palm_door")
wood_polished.append("lament_door")
wood_polished.append("bulbis_door")
wood_polished.append("nightshade_door")
wood_polished.append("ether_door")
# wood_polished -> pressure plates
wood_polished.append("aspen_pressure_plate")
wood_polished.append("baobab_pressure_plate")
wood_polished.append("blue_enchanted_pressure_plate")
wood_polished.append("cherry_pressure_plate")
wood_polished.append("cika_pressure_plate")
wood_polished.append("cypress_pressure_plate")
wood_polished.append("ebony_pressure_plate")
wood_polished.append("fir_pressure_plate")
wood_polished.append("green_enchanted_pressure_plate")
wood_polished.append("holly_pressure_plate")
wood_polished.append("jacaranda_pressure_plate")
wood_polished.append("mahogany_pressure_plate")
wood_polished.append("mangrove_pressure_plate")
wood_polished.append("maple_pressure_plate")
wood_polished.append("pine_pressure_plate")
wood_polished.append("rainbow_eucalyptus_pressure_plate")
wood_polished.append("redwood_pressure_plate")
wood_polished.append("skyris_pressure_plate")
wood_polished.append("willow_pressure_plate")
wood_polished.append("witch_hazel_pressure_plate")
wood_polished.append("zelkova_pressure_plate")
wood_polished.append("sythian_pressure_plate")
wood_polished.append("embur_pressure_plate")
wood_polished.append("palm_pressure_plate")
wood_polished.append("lament_pressure_plate")
wood_polished.append("bulbis_pressure_plate")
wood_polished.append("nightshade_pressure_plate")
wood_polished.append("ether_pressure_plate")
# wood_polished -> buttons
wood_polished.append("aspen_button")
wood_polished.append("baobab_button")
wood_polished.append("blue_enchanted_button")
wood_polished.append("cherry_button")
wood_polished.append("cika_button")
wood_polished.append("cypress_button")
wood_polished.append("ebony_button")
wood_polished.append("fir_button")
wood_polished.append("green_enchanted_button")
wood_polished.append("holly_button")
wood_polished.append("jacaranda_button")
wood_polished.append("mahogany_button")
wood_polished.append("mangrove_button")
wood_polished.append("maple_button")
wood_polished.append("pine_button")
wood_polished.append("rainbow_eucalyptus_button")
wood_polished.append("redwood_button")
wood_polished.append("skyris_button")
wood_polished.append("willow_button")
wood_polished.append("witch_hazel_button")
wood_polished.append("zelkova_button")
wood_polished.append("sythian_button")
wood_polished.append("embur_button")
wood_polished.append("palm_button")
wood_polished.append("lament_button")
wood_polished.append("bulbis_button")
wood_polished.append("nightshade_button")
wood_polished.append("ether_button")
# wood_polished -> trapdoors
wood_polished.append("aspen_trapdoor")
wood_polished.append("baobab_trapdoor")
wood_polished.append("blue_enchanted_trapdoor")
wood_polished.append("cherry_trapdoor")
wood_polished.append("cika_trapdoor")
wood_polished.append("cypress_trapdoor")
wood_polished.append("ebony_trapdoor")
wood_polished.append("fir_trapdoor")
wood_polished.append("green_enchanted_trapdoor")
wood_polished.append("holly_trapdoor")
wood_polished.append("jacaranda_trapdoor")
wood_polished.append("mahogany_trapdoor")
wood_polished.append("mangrove_trapdoor")
wood_polished.append("maple_trapdoor")
wood_polished.append("pine_trapdoor")
wood_polished.append("rainbow_eucalyptus_trapdoor")
wood_polished.append("redwood_trapdoor")
wood_polished.append("skyris_trapdoor")
wood_polished.append("willow_trapdoor")
wood_polished.append("witch_hazel_trapdoor")
wood_polished.append("zelkova_trapdoor")
wood_polished.append("sythian_trapdoor")
wood_polished.append("embur_trapdoor")
wood_polished.append("palm_trapdoor")
wood_polished.append("lament_trapdoor")
wood_polished.append("bulbis_trapdoor")
wood_polished.append("nightshade_trapdoor")
wood_polished.append("ether_trapdoor")
# wood_polished -> fence gates
wood_polished.append("aspen_fence_gate")
wood_polished.append("baobab_fence_gate")
wood_polished.append("blue_enchanted_fence_gate")
wood_polished.append("cherry_fence_gate")
wood_polished.append("cika_fence_gate")
wood_polished.append("cypress_fence_gate")
wood_polished.append("ebony_fence_gate")
wood_polished.append("fir_fence_gate")
wood_polished.append("green_enchanted_fence_gate")
wood_polished.append("holly_fence_gate")
wood_polished.append("jacaranda_fence_gate")
wood_polished.append("mahogany_fence_gate")
wood_polished.append("mangrove_fence_gate")
wood_polished.append("maple_fence_gate")
wood_polished.append("pine_fence_gate")
wood_polished.append("rainbow_eucalyptus_fence_gate")
wood_polished.append("redwood_fence_gate")
wood_polished.append("skyris_fence_gate")
wood_polished.append("willow_fence_gate")
wood_polished.append("witch_hazel_fence_gate")
wood_polished.append("zelkova_fence_gate")
wood_polished.append("sythian_fence_gate")
wood_polished.append("embur_fence_gate")
wood_polished.append("palm_fence_gate")
wood_polished.append("lament_fence_gate")
wood_polished.append("bulbis_fence_gate")
wood_polished.append("nightshade_fence_gate")
wood_polished.append("ether_fence_gate")
# wood_polished -> slabs
wood_polished.append("aspen_slab")
wood_polished.append("baobab_slab")
wood_polished.append("blue_enchanted_slab")
wood_polished.append("cherry_slab")
wood_polished.append("cika_slab")
wood_polished.append("cypress_slab")
wood_polished.append("ebony_slab")
wood_polished.append("fir_slab")
wood_polished.append("green_enchanted_slab")
wood_polished.append("holly_slab")
wood_polished.append("jacaranda_slab")
wood_polished.append("mahogany_slab")
wood_polished.append("mangrove_slab")
wood_polished.append("maple_slab")
wood_polished.append("pine_slab")
wood_polished.append("rainbow_eucalyptus_slab")
wood_polished.append("redwood_slab")
wood_polished.append("skyris_slab")
wood_polished.append("willow_slab")
wood_polished.append("witch_hazel_slab")
wood_polished.append("zelkova_slab")
wood_polished.append("sythian_slab")
wood_polished.append("embur_slab")
wood_polished.append("palm_slab")
wood_polished.append("lament_slab")
wood_polished.append("bulbis_slab")
wood_polished.append("nightshade_slab")
wood_polished.append("ether_slab")
# wood_polished -> stairs
wood_polished.append("aspen_stairs")
wood_polished.append("baobab_stairs")
wood_polished.append("blue_enchanted_stairs")
wood_polished.append("cherry_stairs")
wood_polished.append("cika_stairs")
wood_polished.append("cypress_stairs")
wood_polished.append("ebony_stairs")
wood_polished.append("fir_stairs")
wood_polished.append("green_enchanted_stairs")
wood_polished.append("holly_stairs")
wood_polished.append("jacaranda_stairs")
wood_polished.append("mahogany_stairs")
wood_polished.append("mangrove_stairs")
wood_polished.append("maple_stairs")
wood_polished.append("pine_stairs")
wood_polished.append("rainbow_eucalyptus_stairs")
wood_polished.append("redwood_stairs")
wood_polished.append("skyris_stairs")
wood_polished.append("willow_stairs")
wood_polished.append("witch_hazel_stairs")
wood_polished.append("zelkova_stairs")
wood_polished.append("sythian_stairs")
wood_polished.append("embur_stairs")
wood_polished.append("palm_stairs")
wood_polished.append("lament_stairs")
wood_polished.append("bulbis_stairs")
wood_polished.append("nightshade_stairs")
wood_polished.append("ether_stairs")
# wood_polished -> fences
wood_polished.append("aspen_fence")
wood_polished.append("baobab_fence")
wood_polished.append("blue_enchanted_fence")
wood_polished.append("cherry_fence")
wood_polished.append("cika_fence")
wood_polished.append("cypress_fence")
wood_polished.append("ebony_fence")
wood_polished.append("fir_fence")
wood_polished.append("green_enchanted_fence")
wood_polished.append("holly_fence")
wood_polished.append("jacaranda_fence")
wood_polished.append("mahogany_fence")
wood_polished.append("mangrove_fence")
wood_polished.append("maple_fence")
wood_polished.append("pine_fence")
wood_polished.append("rainbow_eucalyptus_fence")
wood_polished.append("redwood_fence")
wood_polished.append("skyris_fence")
wood_polished.append("willow_fence")
wood_polished.append("witch_hazel_fence")
wood_polished.append("zelkova_fence")
wood_polished.append("sythian_fence")
wood_polished.append("embur_fence")
wood_polished.append("palm_fence")
wood_polished.append("lament_fence")
wood_polished.append("bulbis_fence")
wood_polished.append("nightshade_fence")
wood_polished.append("ether_fence")

stone_bumpy = []
stone_bumpy_content = '{\n    "defaultMaterial": "lumiext:stone_bumpy"\n}'
blocklists.append(stone_bumpy)
block_contents.append(stone_bumpy_content)
# stone_bumpy
stone_bumpy.append("raw_quartz_block")
stone_bumpy.append("purpur_stone")
stone_bumpy.append("ether_stone")
stone_bumpy.append("cryptic_stone")
stone_bumpy.append("black_sandstone")
stone_bumpy.append("white_sandstone")
stone_bumpy.append("blue_sandstone")
stone_bumpy.append("purple_sandstone")
stone_bumpy.append("pink_sandstone")
stone_bumpy.append("black_chiseled_sandstone")
stone_bumpy.append("black_cut_sandstone")
stone_bumpy.append("white_chiseled_sandstone")
stone_bumpy.append("white_cut_sandstone")
stone_bumpy.append("blue_chiseled_sandstone")
stone_bumpy.append("blue_cut_sandstone")
stone_bumpy.append("purple_chiseled_sandstone")
stone_bumpy.append("purple_cut_sandstone")
stone_bumpy.append("pink_chiseled_sandstone")
stone_bumpy.append("pink_cut_sandstone")
stone_bumpy.append("dacite")
stone_bumpy.append("dacite_cobblestone")
stone_bumpy.append("dacite_tile")
stone_bumpy.append("red_rock")
stone_bumpy.append("mossy_stone")
stone_bumpy.append("rocky_stone")
stone_bumpy.append("scoria_stone")
stone_bumpy.append("scoria_cobblestone")
stone_bumpy.append("soapstone")
stone_bumpy.append("soapstone_tile")

stone_bumpy_smooth = []
stone_bumpy_smooth_content = '{\n    "defaultMaterial": "lumiext:stone_bumpy_smooth"\n}'
blocklists.append(stone_bumpy_smooth)
block_contents.append(stone_bumpy_smooth_content)
# stone_bumpy_smooth
stone_bumpy_smooth.append("dacite_bricks")
stone_bumpy_smooth.append("red_rock_bricks")
stone_bumpy_smooth.append("cracked_red_rock_bricks")
stone_bumpy_smooth.append("chiseled_red_rock_bricks")
stone_bumpy_smooth.append("mossy_red_rock_bricks")
stone_bumpy_smooth.append("scoria_stonebricks")
stone_bumpy_smooth.append("soapstone_bricks")
stone_bumpy_smooth.append("black_smooth_sandstone")
stone_bumpy_smooth.append("white_smooth_sandstone")
stone_bumpy_smooth.append("blue_smooth_sandstone")
stone_bumpy_smooth.append("purple_smooth_sandstone")
stone_bumpy_smooth.append("pink_smooth_sandstone")
stone_bumpy_smooth.append("polished_soapstone")

compoundmat_logs = []
compoundmat_logs_content = '{\n    "defaultMaterial": "lumiext:default_bumpy_side",\n    "variants": {\n        "axis=x":{\n            "defaultMaterial": "lumiext:default_bumpy_side_x"\n        },\n        "axis=z":{\n            "defaultMaterial": "lumiext:default_bumpy_side_z"\n        }\n    }\n}'
blocklists.append(compoundmat_logs)
block_contents.append(compoundmat_logs_content)
# compoundmat_logs
compoundmat_logs.append("plant_stem")
compoundmat_logs.append("aspen_log")
compoundmat_logs.append("baobab_log")
# compoundmat_logs.append("blue_enchanted_log")
compoundmat_logs.append("cherry_log")
compoundmat_logs.append("cika_log")
compoundmat_logs.append("cypress_log")
compoundmat_logs.append("ebony_log")
compoundmat_logs.append("fir_log")
# compoundmat_logs.append("green_enchanted_log")
compoundmat_logs.append("holly_log")
compoundmat_logs.append("jacaranda_log")
compoundmat_logs.append("mahogany_log")
compoundmat_logs.append("mangrove_log")
compoundmat_logs.append("maple_log")
compoundmat_logs.append("palo_verde_log")
compoundmat_logs.append("pine_log")
compoundmat_logs.append("rainbow_eucalyptus_log")
compoundmat_logs.append("redwood_log")
compoundmat_logs.append("skyris_log")
compoundmat_logs.append("willow_log")
compoundmat_logs.append("witch_hazel_log")
compoundmat_logs.append("zelkova_log")
compoundmat_logs.append("palm_log")
compoundmat_logs.append("withering_oak_log")
compoundmat_logs.append("nightshade_log")
compoundmat_logs.append("imbued_nightshade_log")
compoundmat_logs.append("ether_log")
compoundmat_logs.append("lament_log")
compoundmat_logs.append("bulbis_stem")

# default_bumpy
default_bumpy = []
default_bumpy_content = '{\n    "defaultMaterial": "lumiext:default_bumpy"\n}'
blocklists.append(default_bumpy)
block_contents.append(default_bumpy_content)
# default_bumpy -> wood
default_bumpy.append("aspen_wood")
default_bumpy.append("baobab_wood")
# default_bumpy.append("blue_enchanted_wood")
default_bumpy.append("cherry_wood")
default_bumpy.append("cika_wood")
default_bumpy.append("cypress_wood")
default_bumpy.append("ebony_wood")
default_bumpy.append("fir_wood")
# default_bumpy.append("green_enchanted_wood")
default_bumpy.append("holly_wood")
default_bumpy.append("jacaranda_wood")
default_bumpy.append("mahogany_wood")
default_bumpy.append("mangrove_wood")
default_bumpy.append("maple_wood")
default_bumpy.append("palo_verde_wood")
default_bumpy.append("pine_wood")
default_bumpy.append("rainbow_eucalyptus_wood")
default_bumpy.append("redwood_wood")
default_bumpy.append("skyris_wood")
default_bumpy.append("willow_wood")
default_bumpy.append("witch_hazel_wood")
default_bumpy.append("zelkova_wood")
default_bumpy.append("palm_wood")
default_bumpy.append("withering_oak_wood")
default_bumpy.append("nightshade_wood")
default_bumpy.append("ether_wood")
default_bumpy.append("lament_wood")
default_bumpy.append("bulbis_wood")

path = "assets/byg/materialmaps/block/{name}.json"
i = 0
for blocklist in blocklists:
    for block in blocklist:
        f = open(path.format(name=block), "w")
        f.write(block_contents[i])
        f.write('\n')
        f.close()
    i += 1
